---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: brats
  - name: cf-environments
run:
  path: buildpacks-ci/tasks/run-brats/run.sh
params:
  BUILDPACK_BRANCH:
  CI_CF_USERNAME:
  CI_CF_PASSWORD:
  LANGUAGE:
  RUBYGEM_MIRROR:
  BOSH_LITE_DOMAIN_NAME:
