# This file holds public configuration (like github uri, github organization) to ease creation of a new pipeline instance.
machete-git-uri-public: https://github.com/SUSE/cf-machete
machete-git-uri: git@github.com:SUSE/cf-machete.git

buildpack-packager-git-uri-public: https://github.com/SUSE/cf-buildpack-packager
buildpack-packager-git-uri: git@github.com:SUSE/cf-buildpack-packager.git

binary-builder-git-uri: https://github.com/SUSE/cf-binary-builder

cf-release-git-uri: https://github.com/cloudfoundry/cf-release

buildpacks-github-org: SUSE
buildpacks-s3-bucket: cf-opensusefs2
bosh-lite-domain-name: cf-app.com

buildpacks-ci-pipeline-uri: http://concourse.suse.de/teams/main/pipelines/cf-buildpacks-ci
buildpacks-ci-git-uri-public: https://github.com/SUSE/cf-buildpacks-ci
public-buildpacks-ci-robots-git-uri-public: https://github.com/SUSE/cf-public-buildpacks-ci-robots
buildpacks-ci-git-uri: git@github.com:SUSE/cf-buildpacks-ci.git
buildpacks-ci-git-uri-public-develop-branch: develop
buildpacks-ci-git-uri-public-branch: master
buildpackapplifecycle-git-branch: develop

buildpacks-docker-ci-repo: splatform/cf-ci-buildpacks
buildpacks-docker-user-email: cf-ci-bot@suse.de
buildpacks-concourse2tracker-docker-repo: cfbuildpacks/concourse2tracker

deployments-git-uri: git@github.com:pivotal-cf/deployments-buildpacks
current-timezone: America/New_York

run-oracle-php-tests: true
oracle-client-libs-s3-bucket: buildpacks-oracle-client-libs
oracle-client-libs-filename: oracle_client_libs.tgz

binary-builder-platform: x86_64
binary-builder-os-name: GNU/Linux
