public-buildpacks-ci-robots-branch: sle12
docker-stack-repository: staging.registry.howdoi.website:443/splatform/rootfs-sle12
buildpacks-docker-username: *docker-internal-username
buildpacks-docker-password: *docker-internal-password

binaries-s3-bucket: cf-sle12
buildpack-dependencies-host-domain: cf-sle12.s3.amazonaws.com

stack-name: sle12
