---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
params:
  TERM: xterm-color
  CI_USERNAME:
  CI_PASSWORD:
run:
  path: bash
  args:
    - "-cl"
    - |
      set -ex
      cd buildpacks-ci
      set +x
      ./scripts/fly-login $CI_USERNAME $CI_PASSWORD
      set -x
      bundle
      rspec --format documentation
      ./scripts/set-status-success
