---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: cassandra-cpp-driver
  - name: cassandra-libuv
  - name: librdkafka
  - name: pecl-amqp
  - name: pecl-cassandra
  - name: pecl-gearman
  - name: pecl-igbinary
  - name: pecl-imagick
  - name: pecl-mailparse
  - name: pecl-memcache
  - name: pecl-mongo
  - name: pecl-msgpack
  - name: pecl-protocolbuffers
  - name: pecl-rdkafka
  - name: pecl-redis
  - name: pecl-solr
  - name: pecl-sundown
  - name: pecl-xdebug
  - name: pecl-yaf
  - name: pecl-mongodb
  - name: pecl-lua
  - name: libmemcached
  - name: lua
  - name: xcache
  - name: ioncube
  - name: rabbitmq-c
  - name: hiredis
  # - name: phpiredis
  #   skipped: since does not yet have releases
  - name: php-protobuf
  - name: cphalcon
  - name: twig
  - name: xhprof
  # - name: suhosin7
  #   skipped: since does not yet have releases
  - name: suhosin5
  - name: buildpacks-ci
run:
  path: bash
  args:
    - '-cl'
    - 'buildpacks-ci/scripts/notifications/create-new-php-modules-versions-story'
params:
  TRACKER_PROJECT_ID:
  TRACKER_API_TOKEN:
  TRACKER_REQUESTER_ID:
