---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpack-checksums
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      cd buildpack-checksums
      if [ -n "${RUBYGEM_MIRROR}" ]; then
        gem sources --clear-all --add ${RUBYGEM_MIRROR}
      fi
      bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
      bundle
      bundle exec rspec
params:
  RUBYGEM_MIRROR:
