---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: deployments-buildpacks
  - name: buildpack
  - name: cf-environments
run:
  path: buildpacks-ci/scripts/test_buildpack
params:
  DEPLOYMENT_NAME:
  STACKS:
  CF_PASSWORD:
