---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: blob
  - name: version
  - name: release
outputs:
  - name: release-artifacts
params:
  BLOB_NAME:
  BLOB_GLOB:
  RELEASE_NAME:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
run:
  path: buildpacks-ci/tasks/create-cflinuxfs2-release/run.sh
