---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: brats
  - name: cf-environments
    path: cf-space
run:
  path: /bin/true
params:
  BUILDPACK_BRANCH:
  LANGUAGE:
  RUBYGEM_MIRROR:
