java-buildpack/java-buildpack-offline-v1.1.zip:
  object_id: b23c8ace-26f2-4270-94ed-a861995826e2
  sha: 886bd2888127429f7f75120d98a187cbf7289c16
  size: 253316417
java-buildpack/java-buildpack-v1.1.zip:
  object_id: 957d975c-43de-4c1e-83a0-6df8f1a2eb1b
  sha: 3ddf6855baec15fb97cd486312615ce82a354dba
  size: 164535
go-buildpack/go_buildpack-cached-v1.1.zip:
  object_id: 5972b6f4-6026-47fd-9864-8b052e8f4a55
  sha: 35ff4ffbde64e185bf221008e1d3aacb81db7d5e
  size: 361547569
