---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: previous-cflinuxfs2-release
  - name: version
  - name: new-cves
  - name: cflinuxfs2
outputs:
  - name: release-body
  - name: new-cves-artifacts
run:
  path: bash
  args:
    - "-cl"
    - "buildpacks-ci/tasks/generate-cflinuxfs2-release-notes/run.rb"
params:
  STACK:
  GITHUB_USERNAME:
  GITHUB_PASSWORD:
