---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpack-checksums
outputs:
  - name: buildpack-checksums-artifacts
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      pushd buildpack-checksums
        export BUNDLE_GEMFILE=$PWD/Gemfile
        if [ ! -z "$RUBYGEM_MIRROR" ]; then
          gem sources --clear-all --add "${RUBYGEM_MIRROR}"
          bundle config mirror.https://rubygems.org "${RUBYGEM_MIRROR}"
        fi
        bundle
        bundle exec ./generate.rb ./final_site
        git add -A
        git commit -m 'Update site' || true
      popd

      rsync -a buildpack-checksums/ buildpack-checksums-artifacts
params:
  RUBYGEM_MIRROR:
