#@data/values
---
language: binary
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  - cflinuxfs5
  - windows
  product_slug: binary-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 1
