#@data/values
---
language: dotnet-core
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: dotnet-core-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 3
