#@data/values
---
language: go
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  - cflinuxfs5
  product_slug: go-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 3
