#@data/values
---
language: java
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: java-buildpack
  branch: feature/go-migration
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 3
