#@data/values
---
language: nodejs
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  - cflinuxfs5
  product_slug: nodejs-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 1
