#@data/values
---
language: nodejs
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: nodejs-buildpack
  skip_docker_start: false
  skip_brats: false
  compute_instance_count: 1
