#@data/values
---
language: php
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: php-buildpack
  skip_docker_start: false
  skip_brats: false
  compute_instance_count: 1
