#@data/values
---
language: ruby
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: ruby-buildpack
  skip_docker_start: false
  skip_brats: false
  compute_instance_count: 3
