#@data/values
---
language: staticfile
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  product_slug: staticfile-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 1
