---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: buildpack-input
  - name: built-out
outputs:
  - name: buildpack
run:
  path: bash
  args:
    - -c
    - |
      set -e
      pushd buildpacks-ci
        bundle install
        bundle exec tasks/update-dependency-in-buildpack/run.rb
      popd
      rsync -a buildpack-input/ buildpack
params:
  DEPENDENCY:
  TRACKER_PROJECT_ID:
  TRACKER_API_TOKEN:
  TRACKER_REQUESTER_ID:
  BUILDPACK_NAME:
  BUILDPACK_DEPENDENCIES_HOST_DOMAIN:
  STACK_NAME:
