---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: public-buildpacks-ci-robots
  - name: gcp-stemcell
  - name: gcp-windows-stemcell
  - name: bosh
  - name: garden-runc
  - name: windows-worker
  - name: concourse
  - name: gcp-cpi
outputs:
  - name: buildpacks-robots-artifacts

run:
  path: bash
  args:
    - -cl
    - |
      cd buildpacks-ci
      bundle exec ./tasks/create-new-bosh-deployment-components-story/run.rb
params:
  TRACKER_PROJECT_ID:
  TRACKER_API_TOKEN:
  TRACKER_REQUESTER_ID:
