---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: bbl-state
  - name: cf-admin-password
outputs:
  - name: integration-config
run:
  path: "buildpacks-ci/tasks/set-up-environment-for-credhub/run.sh"
params:
  CI_CF_USERNAME:
  CI_CF_PASSWORD:
  APPS_DOMAIN:
  ENV_NAME:
