---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: cf-release
  - name: buildpack-bosh-release
  - name: buildpack-github-release
outputs:
  - name: cf-release-artifacts
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/upload-bosh-blobs-to-cf-release/run.rb
params:
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:
  BUILDPACK:
