---
deployment-name: edge-4.buildpacks.ci
resource-pool: cf-edge-environments
cf-manifest-location: deployments-buildpacks/deployments/edge-4.buildpacks.ci/manifest.yml
diego-manifest-location: deployments-buildpacks/deployments/edge-4.buildpacks.ci/diego.yml
