---
deployment-name: edge-1.buildpacks.ci
resource-pool: cf-edge-dea-environments
cf-manifest-location: deployments-buildpacks/deployments/edge-1.buildpacks.ci/manifest.yml
diego-manifest-location: deployments-buildpacks/deployments/edge-1.buildpacks.ci/diego.yml
