---
deployment-name: edge-3.buildpacks.ci
resource-pool: cf-edge-diego-environments
cf-manifest-location: deployments-buildpacks/deployments/edge-3.buildpacks.ci/manifest.yml
diego-manifest-location: deployments-buildpacks/deployments/edge-3.buildpacks.ci/diego.yml
