---
deployment-name: lts-4.buildpacks-gcp.ci
resource-pool: cf-lts-gcp-environments
cf-version: 225
diego-version: 0.1441.0
garden-linux-version: 0.327.0
etcd-version: 18
iaas: gcp
bosh-lite-name: lts-4-gcp-bosh-lite
