name: Find new CVEs

"on":
  workflow_dispatch: { }
  schedule:
    - cron: '0 */2 * * *'

env:
  DB_URI: ${{ secrets.DB_URI }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  NVD_NIST_API_KEY: ${{ secrets.NVD_NIST_API_KEY }}

jobs:
  check-cves:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Find new CVEs
        id: find-new-cves
        uses: cloudfoundry/buildpacks-ci/cve-notification-app/actions/find-new-cves@master
        with:
          db-uri: ${{ env.DB_URI }}
          webhook-url: ${{ env.SLACK_WEBHOOK_URL }}
          nvd-nist-api-key: ${{ env.NVD_NIST_API_KEY }}

      - name: Upload CVEs JSON artifact
        if: ${{ steps.find-new-cves.outputs.new-cves == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: cves.json
          path: ${{ github.workspace }}/cve-notification-app/cves.json
