#[[groups]]
#  labels = ["nodejs", "yarn"]
#  buildpacks = [
#    {id = "org.cloudfoundry.buildpacks.nodejs",         version = "latest" },
#    {id = "org.cloudfoundry.buildpacks.yarn",           version = "latest" }
#  ]

[[groups]]
  labels = ["nodejs", "npm"]
  buildpacks = [
    {id = "org.cloudfoundry.buildpacks.nodejs",         version = "latest" },
    {id = "org.cloudfoundry.buildpacks.npm",            version = "latest" }
  ]

[[groups]]
  labels = [ "java" ]
  buildpacks = [
    { id = "org.cloudfoundry.openjdk",                  version = "latest" },
    { id = "org.cloudfoundry.buildsystem",              version = "latest", optional = true },
    { id = "org.cloudfoundry.jvmapplication",           version = "latest" },

    { id = "org.cloudfoundry.azureapplicationinsights", version = "latest", optional = true },
    { id = "org.cloudfoundry.debug",                    version = "latest", optional = true },
    { id = "org.cloudfoundry.googlestackdriver",        version = "latest", optional = true },
    { id = "org.cloudfoundry.jmx",                      version = "latest", optional = true },

    { id = "org.cloudfoundry.procfile",                 version = "latest", optional = true },
  ]