---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: cf-deployment
  - name: gcp-linux-stemcell
  - name: gcp-windows-stemcell

run:
  path: buildpacks-ci/tasks/recreate-shared-cf-deployment/run.sh
params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  CI_CF_SHARED_PASSWORD:
